/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.event.KeyEvent;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

// *
// * @author Naufal Zaki
// *         TIFRP 19A
// *         19552011155
// *  Teknik Informatika
// ----------------------------------
// * SEKOLAH TINGGI TEKNOLOGI BANDUNG
// ----------------------------------
// */

public class Transaksi_Belanja extends javax.swing.JFrame {
String namabarang;
        int isibox;
        double hargasatuan;
    /**
     * Creates new form Transaksi_Belanja
     */
    public Transaksi_Belanja() {
        initComponents();
        jTextField1.setBackground(new java.awt.Color(0,0,0,1));
        jTextField2.setBackground(new java.awt.Color(0,0,0,1));
        jTextField3.setBackground(new java.awt.Color(0,0,0,1));
        satuan.setBackground(new java.awt.Color(0,0,0,1));
        jTextField5.setBackground(new java.awt.Color(0,0,0,1));
        bayar.setBackground(new java.awt.Color(0,0,0,1));
        jTextArea1.setBackground(new java.awt.Color(0,0,0,1));
    }
    
    public void getTotal() {
        double hargasatuan = Double.parseDouble(satuan.getText());
        double jumlahbeli = Double.parseDouble(jTextField5.getText());
        double bayar = jumlahbeli * hargasatuan;
        jLabel2.setText(String.valueOf(bayar));
    }
    
    
    private void tabelrecord() {
     jTextArea1.setText("======================================================\n" +
                          "\t                     TOKO MAYANG                    \n" +
                          "\t              Jl.Inhoftank no.00 Bandung            \n" +
                          "\t        Tlp.(0274) 869298 / 081227891022            \n" +
                          "======================================================\n" +
                          "                                                      \n" +
                          "    Nama Pelanggan  \t: " + jTextField1.getText() +  "\n" +
                          "    Nama Barang     \t: " + jTextField2.getText() +  "\n" +
                          "    Harga Barang    \t: Rp. " + satuan.getText()+    "\n" +
                          "    Jumlah Beli     \t: " + jTextField5.getText() +  "\n" +
                          "                                                      \n" +
                          "======================================================\n" +
                          "    Total Harga     \t: Rp. " + jLabel2.getText() +  "\n" +  
                          "    Bayar           \t: Rp. " + bayar.getText() +    "\n" + 
                          "    Uang Kembali    \t: Rp. " + jLabel3.getText() +  "\n" +
                          "======================================================\n" +
                          "\t                      Terima Kasih                  \n" +
                          "======================================================");
    }
    
     private void bersihForm() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        satuan.setText("");
        jTextField5.setText("");
        bayar.setText("");
        jLabel3.setText("");
        jLabel2.setText("");
        jTextArea1.setText("");

    }
     
    void filterhuruf(KeyEvent a){
        if(Character.isAlphabetic(a.getKeyChar())){
            a.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom ini Hanya Bisa Memasukan Angka");
        }
    }
    void filterangka (KeyEvent b){
        if(Character.isDigit(b.getKeyChar())){
            b.consume();
            JOptionPane.showMessageDialog(null,"Pada Kolom ini Hanya bisa Memasukan Karakter Huruf");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        satuan = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cetak_warna.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cetak_polos.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 520, 270, 40));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/clear_warna.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/clear_polos.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 570, 270, 40));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/preview_warna.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/preview_polos.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 470, 270, 40));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/buttonbayar_warna.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/buttonbayar_polos.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, -1, 50));

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 220, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField2.setBorder(null);
        jTextField2.setOpaque(false);
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 220, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField3.setBorder(null);
        jTextField3.setOpaque(false);
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 90, 30));

        satuan.setEditable(false);
        satuan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        satuan.setBorder(null);
        satuan.setOpaque(false);
        jPanel1.add(satuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 220, 40));

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField5.setBorder(null);
        jTextField5.setOpaque(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 90, 30));

        bayar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bayar.setBorder(null);
        bayar.setOpaque(false);
        bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bayarKeyTyped(evt);
            }
        });
        jPanel1.add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 620, 80, 30));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "B001", "B002", "B003", "B004", "B005", "B006", "B007", "B008", "B009", "B010" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 574, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 664, 80, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 230, 340));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/latar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
       
        if (jComboBox1.getSelectedIndex() == 1) {
            namabarang="Pulpen";
            isibox=50;
            hargasatuan=2500;
        }else if (jComboBox1.getSelectedIndex() == 2) { 
                  namabarang="Pensil";
                  isibox=30;
                  hargasatuan=2000;
        }else if (jComboBox1.getSelectedIndex() == 3)  {
                  namabarang="Buku";
                  isibox=12;
                  hargasatuan=5000;  
        }else if(jComboBox1.getSelectedIndex() == 4) {
                  namabarang="HVS";
                  isibox=250;
                  hargasatuan=500;
        }else if(jComboBox1.getSelectedIndex() == 5) {
                  namabarang="Penghapus";
                  isibox=20;
                  hargasatuan=1000;
        }else if(jComboBox1.getSelectedIndex() == 6) {
                  namabarang="Tip-X";
                  isibox=1;
                  hargasatuan=6000;  
        }else if(jComboBox1.getSelectedIndex() == 7) {
                  namabarang="Penggaris";
                  isibox=1;
                  hargasatuan=4500; 
        }else if(jComboBox1.getSelectedIndex() == 8) {
                  namabarang="Tas";
                  isibox=1;
                  hargasatuan=300000;
        }else if(jComboBox1.getSelectedIndex() == 9) {
                  namabarang="Spidol";
                  isibox=1;
                  hargasatuan=15000;
        }else if(jComboBox1.getSelectedIndex() == 10) {
                  namabarang="Crayon";
                  isibox=1;
                  hargasatuan=25000;
        }
            jTextField2.setText(String.valueOf(namabarang));
            jTextField3.setText(String.valueOf(isibox));
            satuan.setText(String.valueOf(hargasatuan));
    
   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        // TODO add your handling code here:
        getTotal();
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        double totalbayar,uangbayar,uangkembalian;
        
        totalbayar = Double.parseDouble(jLabel2.getText());
        uangbayar = Double.parseDouble(bayar.getText());
        
        if (uangbayar > totalbayar) {
            uangkembalian = uangbayar - totalbayar;
            jLabel3.setText(""+uangkembalian);
            JOptionPane.showMessageDialog(null, "TerimaKasih,Pembayaran anda berhasil");
            JOptionPane.showMessageDialog(null, "Terimakasih telah berbelanja di Toko Mayang");
        }else if (uangbayar == totalbayar) {
            uangkembalian = uangbayar - totalbayar;
            jLabel3.setText(""+uangkembalian);
            JOptionPane.showMessageDialog(null, "TerimaKasih,Pembayaran anda berhasil");
            JOptionPane.showMessageDialog(null, "Terimakasih telah berbelanja di Toko Mayang");
        }else{
             JOptionPane.showMessageDialog(null, "Maaf, Uang pembayaran kurang");
             bayar.setText("");
        }

       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tabelrecord();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try {

            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Transaksi_Belanja.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        bersihForm();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        // TODO add your handling code here:
       filterangka(evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void bayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bayarKeyTyped
        // TODO add your handling code here:
        filterhuruf(evt);
    }//GEN-LAST:event_bayarKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi_Belanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi_Belanja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField satuan;
    // End of variables declaration//GEN-END:variables
}
